version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
  app:
    build: .
    depends_on:
      - web
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - my-network
  db:			
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
